### ISSUE TITLE
UTF-16 support?

### ISSUE THREAD

**Issue by tadzik** [perl6-community-modules/uri#12]
I got https://github.com/tadzik/Bailador/issues/31 reported for Bailador, is this something that should be fixed on URI's side?

**Comment by ronaldxs** [comment]
Yes - URI::Escape should be extended to handle the case and I will try to do it when I get a chance.  To give a simple example, given the simple html form below with one text field, if you type Æ into the text field every browser I tried (IE, firefox, chrome, opera) came back with a URI the ended in ?sendme=%C6.  If you uncomment the met charset line you get back a URI ending in ?sendme=%C3%86.

```html
<!DOCTYPE HTML>

<html>
<head>
  <title>Text field form</title>
  <!-- meta charset="UTF-8" -->
</head>
<body>
<h3>Text field form</h3>

<form method="get" action="">
<input type="text" name="sendme" />
<input type="submit" value="Submit Text" />
</form>

</body>
</html>
```

**Comment by tadzik** [comment]
Fair enough, thanks for the reply!
