### ISSUE TITLE
cannot install on rakudo-star-2015.09

### ISSUE THREAD

**Issue by szabgab** [perl6-community-modules/uri#17]
$ panda install URI
==> Fetching URI
==> Building URI
==> Testing URI
t/escape.t ............... ok
t/november-urlencoded.t .. ok
Could not parse URI: ftp://ftp.is.co.za/rfc/rfc1808.txt
  in block  at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/URI.pm:42
  in regex unenc-pchar at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:83
  in regex pchar at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:82
  in regex segment-nz-nc at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:77
  in regex path-noscheme at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:71
  in regex relative-part at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:23
  in regex relative-ref at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:20
  in regex URI-reference at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:16
  in regex TOP at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:13
  in method parse at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar.pm:21
  in method parse at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/URI.pm:37
  in method new at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/URI.pm:135
  in block <unit> at t/rfc-3986-examples.t:6

t/rfc-3986-examples.t .... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 22/22 subtests 
Could not parse URI: http://example.com:80/about/us?foo#bar
  in block  at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/URI.pm:42
  in regex unenc-pchar at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:83
  in regex pchar at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:82
  in regex segment-nz-nc at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:77
  in regex path-noscheme at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:71
  in regex relative-part at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:23
  in regex relative-ref at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:20
  in regex URI-reference at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:16
  in regex TOP at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar/URI.pm:13
  in method parse at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/IETF/RFC_Grammar.pm:21
  in method parse at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/URI.pm:37
  in method new at /Users/gabor/work/perl6-lwp-simple/.panda-work/1444478571_1/lib/URI.pm:135
  in block <unit> at t/01.t:10

# Looks like you planned 46 tests, but ran 1
t/01.t ................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 45/46 subtests 

Test Summary Report
-------------------
t/rfc-3986-examples.t  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 22 tests but ran 0.
t/01.t                 (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 46 tests but ran 1.
Files=4, Tests=25,  4 wallclock secs ( 0.05 usr  0.02 sys +  9.36 cusr  0.39 csys =  9.82 CPU)
Result: FAIL
test stage failed for URI: Tests failed
  in method throw at /Users/gabor/rakudo-star-2015.09/install/share/perl6/runtime/CORE.setting.moarvm:1
  in method install at /Users/gabor/rakudo-star-2015.09/install/share/perl6/lib/Panda.pm:142
  in method resolve at /Users/gabor/rakudo-star-2015.09/install/share/perl6/lib/Panda.pm:219
  in sub MAIN at /Users/gabor/rakudo-star-2015.09/install/bin/panda:18
  in block <unit> at /Users/gabor/rakudo-star-2015.09/install/bin/panda:95

Failure Summary
----------------
URI(
	*test stage failed for URI: Tests failed)

air:perl6-lwp-simple gabor$ which perl6
/Users/gabor/rakudo-star-2015.09/install/bin/perl6

**Comment by FROGGS** [comment]
And travis says: ![travis status](https://travis-ci.org/perl6-community-modules/uri.svg?branch=master)

**Comment by FROGGS** [comment]
Can you confirm it is working?

**Comment by szabgab** [comment]
Isn't that build passing on the latest rakudo from Git?
The problem I saw was on rakudo Start 2105.09
BTW could you please link to the Travis-CI page of this repo? I cannot seem to find it.

**Comment by szabgab** [comment]
And then I just found it: https://travis-ci.org/perl6-community-modules/uri

**Comment by moritz** [comment]
@szabgab if you want a version of URI that works with 2015.09, use the one that was shipped with Rakudo Star 2015.09.

Sadly the push/append changes post 2015.09 make it very hard to make URI run on both, so I'm closing this issue as "won't fix".

**Comment by szabgab** [comment]
OK
