### ISSUE TITLE
URI constructor hangs in a thread

### ISSUE THREAD

**Issue by jonathanstowe** [perl6-community-modules/uri#21]
On #perl6 just now:
```
<ollej> I'm having an issue when using the URI module inside a Promise. Unless I've used the URI module before awaiting the result, the program never finishes. Using rakudo 2015.09.
<ollej> I've boiled it down to the following example: await Promise.in(1).then({ say URI.new('http://www.example.com'); });
```

This seems to be the underlying cause of https://rt.perl.org/Ticket/Display.html?id=126390 - it's likely that there is a deeper underlying problem as it is getting deadlocked on a futex() but this is by way of a placeholder in case anyone has a bright idea to work round it in the meantime :)

**Comment by LLFourn** [comment]
You can reproduce it more precisely with

    perl6 -MIETF::RFC_Grammar -e "await Promise.in(1).then({ say IETF::RFC_Grammar.new('rfc3986'); });"

**Comment by ab5tract** [comment]
Does @jdv's patch actually fix this in the end?

**Comment by jonathanstowe** [comment]
It definitely is "fixed", don't know if it was the patch that did it, the examples above and in the https://rt.perl.org/Ticket/Display.html?id=126390 don't hang any more.

I'd say this was safe to close now.
