### ISSUE TITLE
rakudo/rakudo@7e3d0b8369812635097a0db66ae6e4dec3f92833  breaks URI

### ISSUE THREAD

**Issue by GeJ** [perl6-community-modules/uri#25]
... with the following message.

    ===SORRY!=== Error while compiling /home/user/local/share/perl6/site/lib/IETF/RFC_Grammar/URI.pm
    Cannot use adverb version on a type name (only 'ver' and 'auth' are understood)
    at /home/userlocal/share/perl6/site/lib/IETF/RFC_Grammar/URI.pm:11
    ------> version<0.02> is IETF::RFC_Grammar::IPv6⏏;

As I'm not fluent in Perl 6, I can only guess that the aforementioned line should be : 

    unit grammar IETF::RFC_Grammar::URI:ver<0.02> is IETF::RFC_Grammar::IPv6;

Hope this helps.

**Comment by ronaldxs** [comment]
Should be fixed now with latest merge  6bf653b.

**Comment by zoffixznet** [comment]
Indeed, this is fixed now. Someone who can should close this Issue.
